import fetch from 'isomorphic-fetch';
import { IAsset } from 'features/settings';

type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export interface IAssetSearchResponse {
  ok: boolean;
  results: IAssetSearchResponseItem[];
}

export type IAssetSearchResponseItem = Omit<IAsset, 'id' | 'description'>;

interface WebtaskContext {
  query: {
    q?: string;
  };
  secrets: {
    API_KEY: string;
  };
}

type WebtaskRespond = (
  error: null | string,
  body?: IAssetSearchResponse
) => void;
// @ts-ignore
// export = AssetSearch;

async function AssetSearch(context: WebtaskContext, respond: WebtaskRespond) {
  const { API_KEY } = context.secrets;
  if (!API_KEY) return respond('API_KEY secret is not defined.');
  if (!context.query.q || context.query.q.length < 2) {
    return respond(null, { ok: true, results: getDefaultCurrency() });
  }

  const query = decodeURIComponent(context.query.q).toLocaleLowerCase();

  respond(null, {
    ok: true,
    results: [
      ...findPhysicalCurrency(),
      ...findCryptoCurrency(),
      ...(await findSecurities())
    ]
  });

  function getDefaultCurrency(): IAssetSearchResponseItem[] {
    const defaultCurrency = [
      'USD',
      'INR',
      'GBP',
      'AUD',
      'CAD',
      'BRL',
      'EUR',
      'JPY'
    ];

    return defaultCurrency.map((code) => {
      const { name, exp = 2 } = PhysicalCurrencyList[code];
      const asset: IAssetSearchResponseItem = {
        code,
        kind: 'currency',
        name,
        exp
      };

      return asset;
    });
  }

  function findPhysicalCurrency(): IAssetSearchResponseItem[] {
    return Object.entries(PhysicalCurrencyList)
      .filter(
        ([code, { name }]) =>
          code.toLocaleLowerCase().includes(query) ||
          name.toLowerCase().includes(query)
      )
      .slice(0, 10)
      .map(([code, { name, exp = 2 }]) => {
        const asset: IAssetSearchResponseItem = {
          kind: 'currency',
          name,
          code,
          exp
        };

        return asset;
      });
  }

  function findCryptoCurrency(): IAssetSearchResponseItem[] {
    return Object.entries(DigitalCurrencyList)
      .filter(
        ([code, { name }]) =>
          code.toLocaleLowerCase().includes(query) ||
          name.toLowerCase().includes(query)
      )
      .slice(0, 10)
      .map(([code, { name, exp = 8 }]) => {
        const asset: IAssetSearchResponseItem = {
          kind: 'crypto',
          name,
          code,
          exp
        };

        return asset;
      });
  }

  async function findSecurities(): Promise<IAssetSearchResponseItem[]> {
    interface ApiResponseT {
      bestMatches: Array<{
        '1. symbol': string;
        '2. name': string;
        '3. type': string;
        '4. region': string;
        '8. currency': string;
      }>;
    }

    const url = 'https://www.alphavantage.co/query?function=SYMBOL_SEARCH';
    const res = await fetch(`${url}&keywords=${query}&apikey=${API_KEY}`);
    const body: ApiResponseT = await res.json();

    return body.bestMatches.map((item) => {
      const asset: IAssetSearchResponseItem = {
        kind: 'security',
        exp: 4,
        code: item['1. symbol'],
        name: item['2. name'],
        securityType: item['3. type'],
        securityRegion: item['4. region'],
        securityCurrency: item['8. currency']
      };

      return asset;
    });
  }
}

interface CurrencyDataT {
  name: string;
  exp?: number;
  symbol?: string;
}

const PhysicalCurrencyList: Record<string, CurrencyDataT> = {
  AED: { name: 'Emirati Dirham', symbol: '.د.ب', exp: 2 },
  AFN: { name: 'Afghan Afghani', symbol: '؋', exp: 2 },
  ALL: { name: 'Albanian lek', symbol: 'lek', exp: 2 },
  AMD: { name: 'Armenian dram', exp: 2 },
  ANG: { name: 'Dutch Guilder', symbol: 'ƒ', exp: 2 },
  AOA: { name: 'Angolan Kwanza', symbol: 'Kz', exp: 2 },
  ARS: { name: 'Argentine Peso', symbol: '$', exp: 2 },
  AUD: { name: 'Australian Dollar', symbol: '$', exp: 2 },
  AWG: { name: 'Arubin florin', symbol: 'ƒ', exp: 2 },
  AZN: { name: 'Azerbaijani manat', symbol: 'ман', exp: 2 },
  BAM: { name: 'Bosnian Convertible Marka', symbol: 'KM', exp: 2 },
  BBD: { name: 'Barbadian Dollar', symbol: '$', exp: 2 },
  BDT: { name: 'Bangladeshi Taka', symbol: 'Tk', exp: 2 },
  BGN: { name: 'Bulgarian lev', symbol: 'лв', exp: 2 },
  BHD: { name: 'Bahraini Dinar', symbol: '.د.ب or BD', exp: 3 },
  BIF: { name: 'Burundian Franc', symbol: 'FBu', exp: 0 },
  BMD: { name: 'Bermudian Dollar', symbol: '$', exp: 2 },
  BND: { name: 'Bruneian Dollar', symbol: '$', exp: 2 },
  BOB: { name: 'Bolivian Boliviano', symbol: '$b', exp: 2 },
  BRL: { name: 'Brazilian real', symbol: 'R$', exp: 2 },
  BSD: { name: 'Bahamian Dollar', symbol: 'B$', exp: 2 },
  BTN: { name: 'Bhutanese Ngultrum', symbol: 'Nu.', exp: 2 },
  BWP: { name: 'Botswana Pula', symbol: 'P', exp: 2 },
  BYR: { name: 'Belarusian ruble', symbol: 'р', exp: 2 },
  BZD: { name: 'Belize Dollar', symbol: 'BZ$', exp: 2 },
  CAD: { name: 'Canadian Dollar', symbol: '$', exp: 2 },
  CHF: { name: 'Swiss Franc', exp: 2 },
  CLP: { name: 'Chilean Peso', symbol: '$', exp: 0 },
  CNY: { name: 'Yuan or chinese renminbi', symbol: '¥', exp: 2 },
  COP: { name: 'Colombian Peso', symbol: '$', exp: 2 },
  CRC: { name: 'Costa Rican colón', symbol: '₡', exp: 2 },
  CUC: { name: 'Cuban convertible Peso', symbol: '$', exp: 2 },
  CUP: { name: 'Cuban Peso', symbol: '₱', exp: 2 },
  CVE: { name: 'Cape Verdean Escudo', symbol: '$', exp: 0 },
  CZK: { name: 'Czech koruna', symbol: 'Kč', exp: 2 },
  DJF: { name: 'Djiboutian Franc', symbol: 'fdj', exp: 0 },
  DKK: { name: 'Danish krone', symbol: 'kr', exp: 2 },
  DOP: { name: 'Dominican Peso', symbol: '$', exp: 2 },
  DZD: { name: 'Algerian Dinar', symbol: 'جد', exp: 2 },
  EGP: { name: 'Egyptian Pound', symbol: '£ ', exp: 2 },
  ERN: { name: 'Eritrean nakfa', symbol: 'ናቕፋ', exp: 2 },
  ETB: { name: 'Ethiopian Birr', symbol: 'Br', exp: 2 },
  EUR: { name: 'Euro', symbol: '€', exp: 2 },
  FJD: { name: 'Fijian Dollar', symbol: '$', exp: 2 },
  FKP: { name: 'Falkland Island Pound', symbol: '£', exp: 2 },
  GBP: { name: 'British Pound', symbol: '£', exp: 2 },
  GEL: { name: 'Georgian lari', symbol: 'ლ', exp: 2 },
  GHS: { name: 'Ghanaian Cedi', symbol: 'GH¢', exp: 2 },
  GIP: { name: 'Gibraltar pound', symbol: '£', exp: 2 },
  GMD: { name: 'Gambian dalasi', symbol: 'D', exp: 2 },
  GNF: { name: 'Guinean Franc', exp: 0 },
  GTQ: { name: 'Guatemalan Quetzal', symbol: 'Q', exp: 2 },
  GYD: { name: 'Guyanese Dollar', symbol: '$', exp: 2 },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$', exp: 2 },
  HNL: { name: 'Honduran lempira', symbol: 'L', exp: 2 },
  HRK: { name: 'Croatian kuna', symbol: 'kn', exp: 2 },
  HTG: { name: 'Haitian gourde', symbol: 'G', exp: 2 },
  HUF: { name: 'Hungarian forint', symbol: 'Ft', exp: 2 },
  IDR: { name: 'Indonesian Rupiah', symbol: 'Rp', exp: 2 },
  ILS: { name: 'Israeli Shekel', symbol: '₪', exp: 2 },
  INR: { name: 'Indian Rupee', symbol: '₹', exp: 2 },
  IQD: { name: 'Iraqi Dinar', symbol: 'ع.د', exp: 3 },
  IRR: { name: 'Iranian Rial', symbol: '﷼', exp: 2 },
  ISK: { name: 'Icelandic Krona', symbol: 'kr', exp: 0 },
  JMD: { name: 'Jamaican Dollar', symbol: 'J$', exp: 2 },
  JOD: { name: 'Jordanian Dinar', exp: 3 },
  JPY: { name: 'Japanese yen', symbol: '¥', exp: 0 },
  KES: { name: 'Kenyan Shilling', symbol: 'KSh', exp: 2 },
  KGS: { name: 'Kyrgyzstani som', symbol: 'лв', exp: 2 },
  KHR: { name: 'Cambodian Riel', symbol: '៛', exp: 2 },
  KMF: { name: 'Comoro Franc', exp: 0 },
  KPW: { name: 'North Korean won', symbol: '₩', exp: 2 },
  KRW: { name: 'South Korean won', symbol: '₩', exp: 0 },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'ك', exp: 3 },
  KYD: { name: 'Caymanian Dollar', symbol: '$', exp: 2 },
  KZT: { name: 'Kazakhstani tenge', symbol: '₸', exp: 2 },
  LAK: { name: 'Lao or Laotian Kip', symbol: '₭', exp: 2 },
  LBP: { name: 'Lebanese Pound', symbol: 'ل.ل', exp: 2 },
  LKR: { name: 'Sri Lankan Rupee', symbol: 'Rs', exp: 2 },
  LRD: { name: 'Liberian Dollar', symbol: '$', exp: 2 },
  LSL: { name: 'Lesotho loti', symbol: 'L or M', exp: 2 },
  LTL: { name: 'Lithuanian litas', symbol: 'Lt', exp: 2 },
  LYD: { name: 'Libyan Dinar', symbol: ' د.ل', exp: 3 },
  MAD: { name: 'Moroccan Dirham', symbol: 'م.د.', exp: 2 },
  MDL: { name: 'Moldovan Leu', symbol: 'L', exp: 2 },
  MGA: { name: 'Malagasy Ariary', symbol: 'Ar', exp: 2 },
  MKD: { name: 'Macedonian Denar', symbol: 'ден', exp: 2 },
  MMK: { name: 'Burmese Kyat', symbol: 'K', exp: 2 },
  MNT: { name: 'Mongolian Tughrik', symbol: '₮', exp: 2 },
  MOP: { name: 'Macau Pataca', symbol: 'MOP$', exp: 2 },
  MRO: { name: 'Mauritanian Ouguiya', symbol: 'UM', exp: 2 },
  MUR: { name: 'Mauritian rupee', symbol: 'Rs', exp: 2 },
  MVR: { name: 'Maldivian Rufiyaa', symbol: 'rf', exp: 2 },
  MWK: { name: 'Malawian Kwacha', symbol: 'MK', exp: 2 },
  MXN: { name: 'Mexico Peso', symbol: '$', exp: 2 },
  MYR: { name: 'Malaysian Ringgit', symbol: 'RM', exp: 2 },
  MZN: { name: 'Mozambican Metical', symbol: 'MT', exp: 2 },
  NAD: { name: 'Namibian Dollar', symbol: '$', exp: 2 },
  NGN: { name: 'Nigerian Naira', symbol: '₦', exp: 2 },
  NIO: { name: 'Nicaraguan córdoba', symbol: 'C$', exp: 2 },
  NOK: { name: 'Norwegian krone', symbol: 'kr', exp: 2 },
  NPR: { name: 'Nepalese Rupee', symbol: 'Rs', exp: 2 },
  NZD: { name: 'New Zealand Dollar', symbol: '$', exp: 2 },
  OMR: { name: 'Omani Rial', symbol: 'ع.ر.', exp: 3 },
  PAB: { name: 'Balboa panamérn', symbol: 'B/', exp: 2 },
  PEN: { name: 'Peruvian nuevo sol', symbol: 'S/', exp: 2 },
  PGK: { name: 'Papua New Guinean Kina', symbol: 'K', exp: 2 },
  PHP: { name: 'Philippine Peso', symbol: '₱', exp: 2 },
  PKR: { name: 'Pakistani Rupee', symbol: 'Rs', exp: 2 },
  PLN: { name: 'Polish złoty', symbol: 'zł', exp: 2 },
  PYG: { name: 'Paraguayan guarani', symbol: '₲', exp: 0 },
  QAR: { name: 'Qatari Riyal', symbol: 'ق.ر ', exp: 2 },
  RON: { name: 'Romanian leu', symbol: 'lei', exp: 2 },
  RSD: { name: 'Serbian Dinar', symbol: 'РСД', exp: 2 },
  RUB: { name: 'Russian Rouble', symbol: '₽', exp: 2 },
  RWF: { name: 'Rwandan franc', symbol: 'FRw, RF, R₣', exp: 0 },
  SAR: { name: 'Saudi Arabian Riyal', symbol: 'ر.س', exp: 2 },
  SBDf: { name: 'Solomon Islander Dollar', symbol: 'SI$', exp: 2 },
  SCR: { name: 'Seychellois Rupee', symbol: 'Rs', exp: 2 },
  SDG: { name: 'Sudanese Pound', exp: 2 },
  SEK: { name: 'Swedish krona', symbol: 'kr', exp: 2 },
  SGD: { name: 'Singapore Dollar', symbol: '$', exp: 2 },
  SLL: { name: 'Sierra Leonean Leone', symbol: 'Le', exp: 2 },
  SOS: { name: 'Somali Shilling', symbol: 'S', exp: 2 },
  SRD: { name: 'Surinamese Dollar', symbol: '$', exp: 2 },
  SYP: { name: 'Syrian Pound', symbol: '£', exp: 2 },
  SZL: { name: 'Swazi Lilangeni', symbol: 'L or E', exp: 2 },
  THB: { name: 'Thai Baht', symbol: '฿', exp: 2 },
  TJS: { name: 'Tajikistani somoni', exp: 2 },
  TMT: { name: 'Turkmenistan manat', symbol: 'T', exp: 2 },
  TND: { name: 'Tunisian Dinar', exp: 3 },
  TOP: { name: "Tongan Pa'anga", symbol: 'T$', exp: 2 },
  TRY: { name: 'Turkish Lira', symbol: '₺', exp: 2 },
  TTD: { name: 'Trinidadian Dollar', symbol: 'TT$', exp: 2 },
  TWD: { name: 'Taiwan New Dollar', symbol: 'NT$', exp: 2 },
  TZS: { name: 'Tanzanian Shilling', symbol: 'Sh', exp: 2 },
  UAH: { name: 'Ukrainian Hryvnia', symbol: '₴', exp: 2 },
  UGX: { name: 'Ugandan Shilling', symbol: 'USh', exp: 0 },
  USD: { name: 'US Dollar', symbol: '$', exp: 2 },
  UYU: { name: 'Uruguayan Peso', symbol: '$U', exp: 2 },
  UZS: { name: 'Uzbekistani som', symbol: 'лв', exp: 2 },
  VEF: { name: 'Venezuelan bolivar', symbol: 'Bs', exp: 2 },
  VND: { name: 'Vietnamese Dong', symbol: '₫', exp: 0 },
  VUV: { name: 'Vanuatu Vatu', symbol: 'VT', exp: 0 },
  WST: { name: 'Samoan Tālā', symbol: '$', exp: 2 },
  YER: { name: 'Yemeni Rial', exp: 2 },
  ZAR: { name: 'South African Rand', symbol: 'R', exp: 2 },
  ZMW: { name: 'Zambian Kwacha', exp: 2 },
  ZWD: { name: 'Zimbabwean Dollar', symbol: 'Z$', exp: 2 },
  XAG: { name: 'Silver Ounce', exp: 2 },
  XAU: { name: 'Gold Ounce', exp: 2 }
};

const DigitalCurrencyList: Record<string, CurrencyDataT> = {
  '808': { name: '808Coin' },
  '1ST': { name: 'FirstBlood' },
  '2GIVE': { name: 'GiveCoin' },
  ABT: { name: 'ArcBlock' },
  ABY: { name: 'ArtByte' },
  AC: { name: 'AsiaCoin' },
  ACT: { name: 'Achain' },
  ADA: { name: 'Cardano' },
  ADT: { name: 'adToken' },
  ADX: { name: 'AdEx' },
  AE: { name: 'Aeternity' },
  AEON: { name: 'Aeon' },
  AGI: { name: 'SingularityNET' },
  AGRS: { name: 'IDNI-Agoras' },
  AI: { name: 'POLY-AI' },
  AID: { name: 'AidCoin' },
  AION: { name: 'Aion' },
  AIR: { name: 'AirToken' },
  AKY: { name: 'Akuya-Coin' },
  ALIS: { name: 'ALIS' },
  AMBER: { name: 'AmberCoin' },
  AMP: { name: 'Synereo' },
  ANC: { name: 'Anoncoin' },
  ANT: { name: 'Aragon' },
  APPC: { name: 'AppCoins' },
  APX: { name: 'APX-Ventures' },
  ARDR: { name: 'Ardor' },
  ARK: { name: 'Ark' },
  ARN: { name: 'Aeron' },
  AST: { name: 'AirSwap' },
  ATB: { name: 'ATBCoin' },
  ATM: { name: 'ATMChain' },
  ATS: { name: 'Authorship' },
  AUR: { name: 'Auroracoin' },
  AVT: { name: 'Aventus' },
  B3: { name: 'B3Coin' },
  BAT: { name: 'Basic-Attention-Token' },
  BAY: { name: 'BitBay' },
  BBR: { name: 'Boolberry' },
  BCAP: { name: 'BCAP' },
  BCC: { name: 'BitConnect' },
  BCD: { name: 'Bitcoin-Diamond' },
  BCH: { name: 'Bitcoin-Cash' },
  BCN: { name: 'Bytecoin' },
  BCPT: { name: 'BlockMason-Credit-Protocol-Token' },
  BCX: { name: 'BitcoinX' },
  BCY: { name: 'BitCrystals' },
  BDL: { name: 'Bitdeal' },
  BEE: { name: 'Bee-Token' },
  BELA: { name: 'BelaCoin' },
  BET: { name: 'DAO-Casino' },
  BFT: { name: 'BF-Token' },
  BIS: { name: 'Bismuth' },
  BITB: { name: 'BitBean' },
  BITBTC: { name: 'BitBTC' },
  BITCNY: { name: 'BitCNY' },
  BITEUR: { name: 'BitEUR' },
  BITGOLD: { name: 'BitGOLD' },
  BITSILVER: { name: 'BitSILVER' },
  BITUSD: { name: 'BitUSD' },
  BIX: { name: 'Bibox-Token' },
  BLITZ: { name: 'Blitzcash' },
  BLK: { name: 'Blackcoin' },
  BLN: { name: 'Bolenum' },
  BLOCK: { name: 'Blocknet' },
  BLZ: { name: 'Bluzelle' },
  BMC: { name: 'Blackmoon-Crypto' },
  BNB: { name: 'Binance-Coin' },
  BNT: { name: 'Bancor-Network-Token' },
  BNTY: { name: 'Bounty0x' },
  BOST: { name: 'BoostCoin' },
  BOT: { name: 'Bodhi' },
  BQ: { name: 'bitqy' },
  BRD: { name: 'Bread' },
  BRK: { name: 'Breakout-Coin' },
  BRX: { name: 'Breakout-Stake' },
  BTA: { name: 'Bata' },
  BTC: { name: 'Bitcoin' },
  BTCD: { name: 'BitcoinDark' },
  BTCP: { name: 'Bitcoin-Private' },
  BTG: { name: 'Bitcoin-Gold' },
  BTM: { name: 'Bitmark' },
  BTS: { name: 'BitShares' },
  BTSR: { name: 'BTSR' },
  BTX: { name: 'Bitcore' },
  BURST: { name: 'Burstcoin' },
  BUZZ: { name: 'BuzzCoin' },
  BYC: { name: 'Bytecent' },
  BYTOM: { name: 'Bytom' },
  C20: { name: 'Crypto20' },
  CANN: { name: 'CannabisCoin' },
  CAT: { name: 'BlockCAT' },
  CCRB: { name: 'CryptoCarbon' },
  CDT: { name: 'Blox' },
  CFI: { name: 'Cofound-it' },
  CHAT: { name: 'ChatCoin' },
  CHIPS: { name: 'Chips' },
  CLAM: { name: 'Clams' },
  CLOAK: { name: 'CloakCoin' },
  CMP: { name: 'Compcoin' },
  CMT: { name: 'CyberMiles' },
  CND: { name: 'Cindicator' },
  CNX: { name: 'Cryptonex' },
  COFI: { name: 'CoinFi' },
  COSS: { name: 'COSS' },
  COVAL: { name: 'Circuits-Of-Value' },
  CRBIT: { name: 'CreditBIT' },
  CREA: { name: 'CreativeCoin' },
  CREDO: { name: 'Credo' },
  CRW: { name: 'Crown' },
  CSNO: { name: 'BitDice' },
  CTR: { name: 'Centra' },
  CTXC: { name: 'Cortex' },
  CURE: { name: 'CureCoin' },
  CVC: { name: 'Civic' },
  DAI: { name: 'Dai' },
  DAR: { name: 'Darcrus' },
  DASH: { name: 'Dash' },
  DATA: { name: 'DATAcoin' },
  DAY: { name: 'Chronologic' },
  DBC: { name: 'DeepBrain-Chain' },
  DBIX: { name: 'DubaiCoin' },
  DCN: { name: 'Dentacoin' },
  DCR: { name: 'Decred' },
  DCT: { name: 'DECENT' },
  DDF: { name: 'Digital-Developers-Fund' },
  DENT: { name: 'Dent' },
  DFS: { name: 'DFSCoin' },
  DGB: { name: 'DigiByte' },
  DGC: { name: 'Digitalcoin' },
  DGD: { name: 'DigixDAO' },
  DICE: { name: 'Etheroll' },
  DLT: { name: 'Agrello-Delta' },
  DMD: { name: 'Diamond' },
  DMT: { name: 'DMarket' },
  DNT: { name: 'district0x' },
  DOGE: { name: 'DogeCoin' },
  DOPE: { name: 'DopeCoin' },
  DRGN: { name: 'Dragonchain' },
  DTA: { name: 'Data' },
  DTB: { name: 'Databits' },
  DYN: { name: 'Dynamic' },
  EAC: { name: 'EarthCoin' },
  EBST: { name: 'eBoost' },
  EBTC: { name: 'eBTC' },
  ECC: { name: 'ECC' },
  ECN: { name: 'E-coin' },
  EDG: { name: 'Edgeless' },
  EDO: { name: 'Eidoo' },
  EFL: { name: 'Electronic-Gulden' },
  EGC: { name: 'EverGreenCoin' },
  EKT: { name: 'EDUCare' },
  ELA: { name: 'Elastos' },
  ELEC: { name: 'Electrify.Asia' },
  ELF: { name: 'aelf' },
  ELIX: { name: 'Elixir' },
  EMB: { name: 'Embercoin' },
  EMC: { name: 'Emercoin' },
  EMC2: { name: 'Einsteinium' },
  ENG: { name: 'Enigma' },
  ENJ: { name: 'Enjin-Coin' },
  ENRG: { name: 'EnergyCoin' },
  EOS: { name: 'EOS' },
  EOT: { name: 'EOT-Token' },
  EQT: { name: 'EquiTrader' },
  ERC: { name: 'EuropeCoin' },
  ETC: { name: 'Ethereum-Classic' },
  ETH: { name: 'Ethereum' },
  ETHD: { name: 'Ethereum-Dark' },
  ETHOS: { name: 'Ethos' },
  ETN: { name: 'Electroneum' },
  ETP: { name: 'Metaverse-Entropy' },
  ETT: { name: 'EncryptoTel' },
  EVE: { name: 'Devery' },
  EVX: { name: 'Everex' },
  EXCL: { name: 'ExclusiveCoin' },
  EXP: { name: 'Expanse' },
  FCT: { name: 'Factom' },
  FLDC: { name: 'FoldingCoin' },
  FLO: { name: 'FlorinCoin' },
  FLT: { name: 'FlutterCoin' },
  FRST: { name: 'FirstCoin' },
  FTC: { name: 'Feathercoin' },
  FUEL: { name: 'Etherparty' },
  FUN: { name: 'FunFair' },
  GAM: { name: 'Gambit' },
  GAME: { name: 'GameCredits' },
  GAS: { name: 'Gas' },
  GBG: { name: 'Golos Gold' },
  GBX: { name: 'GoByte' },
  GBYTE: { name: 'Byteball' },
  GCR: { name: 'GCRCoin' },
  GEO: { name: 'GeoCoin' },
  GLD: { name: 'GoldCoin' },
  GNO: { name: 'Gnosis-Token' },
  GNT: { name: 'Golem-Tokens' },
  GOLOS: { name: 'Golos' },
  GRC: { name: 'Gridcoin' },
  GRS: { name: 'Groestlcoin' },
  GRWI: { name: 'Growers-International' },
  GTC: { name: 'Game' },
  GTO: { name: 'Gifto' },
  GUP: { name: 'Guppy' },
  GVT: { name: 'Genesis-Vision' },
  GXS: { name: 'GXShares' },
  HBN: { name: 'HoboNickels' },
  HEAT: { name: 'HEAT' },
  HMQ: { name: 'Humaniq' },
  HPB: { name: 'High-Performance-Blockchain' },
  HSR: { name: 'Hshare' },
  HUSH: { name: 'Hush' },
  HVN: { name: 'Hive' },
  HXX: { name: 'HexxCoin' },
  ICN: { name: 'ICONOMI' },
  ICX: { name: 'ICON' },
  IFC: { name: 'Infinitecoin' },
  IFT: { name: 'investFeed' },
  IGNIS: { name: 'Ignis' },
  INCNT: { name: 'Incent' },
  IND: { name: 'Indorse-Token' },
  INF: { name: 'InfChain' },
  INK: { name: 'Ink' },
  INS: { name: 'INS-Ecosystem' },
  INSTAR: { name: 'Insights-Network' },
  INT: { name: 'Internet-Node-Token' },
  INXT: { name: 'Internxt' },
  IOC: { name: 'IOCoin' },
  ION: { name: 'ION' },
  IOP: { name: 'Internet-of-People' },
  IOST: { name: 'IOStoken' },
  IOTA: { name: 'IOTA' },
  IOTX: { name: 'IoTeX' },
  IQT: { name: 'Iquant-Chain' },
  ITC: { name: 'IoT-Chain' },
  IXC: { name: 'iXcoin' },
  IXT: { name: 'InsureX' },
  J8T: { name: 'JET8' },
  JNT: { name: 'Jibrel-Network' },
  KCS: { name: 'KuCoin' },
  KICK: { name: 'KickCoin' },
  KIN: { name: 'KIN' },
  KMD: { name: 'Komodo' },
  KNC: { name: 'Kyber-Network' },
  KORE: { name: 'KoreCoin' },
  LBC: { name: 'LBRY-Credits' },
  LCC: { name: 'Litecoin-Cash' },
  LEND: { name: 'EthLend' },
  LEV: { name: 'Leverj' },
  LGD: { name: 'Legends-Room' },
  LINDA: { name: 'Linda' },
  LINK: { name: 'ChainLink' },
  LKK: { name: 'Lykke' },
  LMC: { name: 'LoMoCoin' },
  LOCI: { name: 'LOCIcoin' },
  LOOM: { name: 'Loom-Token' },
  LRC: { name: 'Loopring' },
  LSK: { name: 'Lisk' },
  LTC: { name: 'Litecoin' },
  LUN: { name: 'Lunyr' },
  MAID: { name: 'MaidSafeCoin' },
  MANA: { name: 'Decentraland' },
  MAX: { name: 'Maxcoin' },
  MBRS: { name: 'Embers' },
  MCAP: { name: 'MCAP' },
  MCO: { name: 'Monaco' },
  MDA: { name: 'Moeda-Loyalty-Points' },
  MEC: { name: 'Megacoin' },
  MED: { name: 'MediBlock' },
  MEME: { name: 'Memetic' },
  MER: { name: 'Mercury' },
  MGC: { name: 'MergeCoin' },
  MGO: { name: 'MobileGo' },
  MINEX: { name: 'Minex' },
  MINT: { name: 'Mintcoin' },
  MITH: { name: 'Mithril' },
  MKR: { name: 'Maker' },
  MLN: { name: 'Melon' },
  MNE: { name: 'Minereum' },
  MNX: { name: 'MinexCoin' },
  MOD: { name: 'Modum' },
  MONA: { name: 'MonaCoin' },
  MRT: { name: 'Miners-Reward-Token' },
  MSP: { name: 'Mothership' },
  MTH: { name: 'Monetha' },
  MTN: { name: 'MedToken' },
  MUE: { name: 'MonetaryUnit' },
  MUSIC: { name: 'Musicoin' },
  MYB: { name: 'MyBit-Token' },
  MYST: { name: 'Mysterium' },
  MZC: { name: 'Mazacoin' },
  NAMO: { name: 'Namocoin' },
  NANO: { name: 'Nano' },
  NAS: { name: 'Nebulas-Token' },
  NAV: { name: 'Nav-Coin' },
  NBT: { name: 'NuBits' },
  NCASH: { name: 'Nucleus-Vision' },
  NDC: { name: 'NeverDie-Coin' },
  NEBL: { name: 'Neblio' },
  NEO: { name: 'NEO' },
  NEOS: { name: 'NeosCoin' },
  NET: { name: 'Nimiq' },
  NLC2: { name: 'NoLimitCoin' },
  NLG: { name: 'Gulden' },
  NMC: { name: 'Namecoin' },
  NMR: { name: 'Numeraire' },
  NOBL: { name: 'NobleCoin' },
  NOTE: { name: 'DNotes' },
  NPXS: { name: 'Pundi-X-Token' },
  NSR: { name: 'NuShares' },
  NTO: { name: 'Fujinto' },
  NULS: { name: 'Nuls' },
  NVC: { name: 'Novacoin' },
  NXC: { name: 'Nexium' },
  NXS: { name: 'Nexus' },
  NXT: { name: 'Nxt' },
  OAX: { name: 'openANX' },
  OBITS: { name: 'Obits' },
  OCL: { name: 'Oceanlab' },
  OCN: { name: 'Odyssey' },
  ODEM: { name: 'ODEM' },
  ODN: { name: 'Obsidian' },
  OF: { name: 'OFCOIN' },
  OK: { name: 'OKCash' },
  OMG: { name: 'OmiseGo' },
  OMNI: { name: 'Omni' },
  ONION: { name: 'DeepOnion' },
  ONT: { name: 'Ontology' },
  OPT: { name: 'Opus' },
  OST: { name: 'Simple-Token' },
  PART: { name: 'Particl' },
  PASC: { name: 'PascalCoin' },
  PAY: { name: 'TenX' },
  PBL: { name: 'Pebbles' },
  PBT: { name: 'Primalbase-Token' },
  PFR: { name: 'Payfair' },
  PING: { name: 'CryptoPing' },
  PINK: { name: 'Pinkcoin' },
  PIVX: { name: 'PIVX' },
  PIX: { name: 'Lampix' },
  PLBT: { name: 'Polybius' },
  PLR: { name: 'Pillar' },
  PLU: { name: 'Pluton' },
  POA: { name: 'POA-Network' },
  POE: { name: 'Poet' },
  POLY: { name: 'Polymath' },
  POSW: { name: 'PoSW-Coin' },
  POT: { name: 'PotCoin' },
  POWR: { name: 'Power-Ledger' },
  PPC: { name: 'Peercoin' },
  PPT: { name: 'Populous' },
  PPY: { name: 'Peerplays' },
  PRG: { name: 'Paragon-Coin' },
  PRL: { name: 'Oyster-Pearl' },
  PRO: { name: 'Propy' },
  PST: { name: 'Primas' },
  PTC: { name: 'Pesetacoin' },
  PTOY: { name: 'Patientory' },
  PURA: { name: 'Pura' },
  QASH: { name: 'QASH' },
  QAU: { name: 'Quantum' },
  QLC: { name: 'Qlink' },
  QRK: { name: 'Quark' },
  QRL: { name: 'Quantum-Resistant-Ledger' },
  QSP: { name: 'Quantstamp' },
  QTL: { name: 'Quatloo' },
  QTUM: { name: 'Qtum' },
  QWARK: { name: 'Qwark' },
  R: { name: 'Revain' },
  RADS: { name: 'Radium' },
  RAIN: { name: 'Condensate' },
  RBIES: { name: 'Rubies' },
  RBX: { name: 'Ripto-Bux' },
  RBY: { name: 'RubyCoin' },
  RCN: { name: 'Ripio-Credit-Network' },
  RDD: { name: 'ReddCoin' },
  RDN: { name: 'Raiden-Network-Token' },
  REC: { name: 'Regalcoin' },
  RED: { name: 'Redcoin' },
  REP: { name: 'Augur' },
  REQ: { name: 'Request-Network' },
  RHOC: { name: 'RChain' },
  RIC: { name: 'Riecoin' },
  RISE: { name: 'Rise' },
  RLC: { name: 'RLC-Token' },
  RLT: { name: 'RouletteToken' },
  RPX: { name: 'Red-Pulse' },
  RRT: { name: 'Recovery-Right-Tokens' },
  RUFF: { name: 'Ruff' },
  RUP: { name: 'Rupee' },
  RVT: { name: 'Rivetz' },
  SAFEX: { name: 'SafeExchangeCoin' },
  SALT: { name: 'Salt' },
  SAN: { name: 'Santiment-Network-Token' },
  SBD: { name: 'Steem-Dollars' },
  SBTC: { name: 'Super-Bitcoin' },
  SC: { name: 'Siacoin' },
  SEELE: { name: 'Seele' },
  SEQ: { name: 'Sequence' },
  SHIFT: { name: 'SHIFT' },
  SIB: { name: 'SIBCoin' },
  SIGMA: { name: 'SIGMAcoin' },
  SIGT: { name: 'Signatum' },
  SJCX: { name: 'Storjcoin-X' },
  SKIN: { name: 'SkinCoin' },
  SKY: { name: 'Skycoin' },
  SLR: { name: 'SolarCoin' },
  SLS: { name: 'SaluS' },
  SMART: { name: 'SmartCash' },
  SMT: { name: 'SmartMesh' },
  SNC: { name: 'SunContract' },
  SNGLS: { name: 'SingularDTV' },
  SNM: { name: 'SONM' },
  SNRG: { name: 'Synergy' },
  SNT: { name: 'Status-Network-Token' },
  SOC: { name: 'All-Sports' },
  SOUL: { name: 'Phantasma' },
  SPANK: { name: 'SpankChain' },
  SPC: { name: 'SpaceChain' },
  SPHR: { name: 'Sphere' },
  SPR: { name: 'SpreadCoin' },
  SRN: { name: 'Sirin-Labs-Token' },
  START: { name: 'Startcoin' },
  STEEM: { name: 'Steem' },
  STK: { name: 'STK-Token' },
  STORJ: { name: 'Storj' },
  STORM: { name: 'Storm' },
  STQ: { name: 'Storiqa' },
  STRAT: { name: 'Stratis' },
  STX: { name: 'Stox' },
  SUB: { name: 'Substratum' },
  SWFTC: { name: 'SwftCoin' },
  SWIFT: { name: 'Bitswift' },
  SWT: { name: 'Swarm-City' },
  SYNX: { name: 'Syndicate' },
  SYS: { name: 'SysCoin' },
  TAAS: { name: 'Taas' },
  TAU: { name: 'Lamden' },
  TCC: { name: 'The-ChampCoin' },
  TFL: { name: 'True-Flip' },
  THC: { name: 'HempCoin' },
  THETA: { name: 'Theta-Token' },
  TIME: { name: 'Time' },
  TIX: { name: 'Blocktix' },
  TKN: { name: 'TokenCard' },
  TKR: { name: 'Trackr' },
  TKS: { name: 'Tokes' },
  TNB: { name: 'Time-New-Bank' },
  TNT: { name: 'Tierion' },
  TOA: { name: 'ToaCoin' },
  TRAC: { name: 'OriginTrail' },
  TRC: { name: 'Terracoin' },
  TRCT: { name: 'Tracto' },
  TRIG: { name: 'Triggers' },
  TRST: { name: 'Trustcoin' },
  TRUE: { name: 'TrueChain' },
  TRUST: { name: 'TrustPlus' },
  TRX: { name: 'Tronix' },
  TUSD: { name: 'TrueUSD' },
  TX: { name: 'TransferCoin' },
  UBQ: { name: 'Ubiq' },
  UKG: { name: 'UnikoinGold' },
  ULA: { name: 'Ulatech' },
  UNB: { name: 'UnbreakableCoin' },
  UNITY: { name: 'SuperNET' },
  UNO: { name: 'Unobtanium' },
  UNY: { name: 'Unity-Ingot' },
  UP: { name: 'UpToken' },
  URO: { name: 'Uro' },
  USDT: { name: 'Tether' },
  UTK: { name: 'UTrust' },
  VEE: { name: 'BLOCKv' },
  VEN: { name: 'VeChain' },
  VERI: { name: 'Veritaseum' },
  VIA: { name: 'Viacoin' },
  VIB: { name: 'Viberate' },
  VIBE: { name: 'Vibe' },
  VIVO: { name: 'VIVO' },
  VOISE: { name: 'Voise' },
  VOX: { name: 'Voxels' },
  VPN: { name: 'VPNCoin' },
  VRC: { name: 'Vericoin' },
  VRM: { name: 'Verium' },
  VRS: { name: 'Veros' },
  VSL: { name: 'vSlice' },
  VTC: { name: 'Vertcoin' },
  VTR: { name: 'vTorrent' },
  WABI: { name: 'WaBi' },
  WAN: { name: 'Wanchain' },
  WAVES: { name: 'Waves' },
  WAX: { name: 'Wax-Token' },
  WCT: { name: 'Waves-Community' },
  WDC: { name: 'WorldCoin' },
  WGO: { name: 'WavesGo' },
  WGR: { name: 'Wagerr' },
  WINGS: { name: 'Wings' },
  WPR: { name: 'WePower' },
  WTC: { name: 'Walton' },
  WTT: { name: 'Giga-Watt-Token' },
  XAS: { name: 'Asch' },
  XAUR: { name: 'Xaurum' },
  XBC: { name: 'Bitcoin-Plus' },
  XBY: { name: 'XtraBYtes' },
  XCN: { name: 'Cryptonite' },
  XCP: { name: 'Counterparty' },
  XDN: { name: 'DigitalNote' },
  XEL: { name: 'Elastic' },
  XEM: { name: 'NEM' },
  XID: { name: 'Sphere-Identity' },
  XLM: { name: 'Stellar' },
  XMG: { name: 'Magi' },
  XMR: { name: 'Monero' },
  XMT: { name: 'Metal' },
  XMY: { name: 'Myriadcoin' },
  XPM: { name: 'Primecoin' },
  XRL: { name: 'Rialto' },
  XRP: { name: 'Ripple' },
  XSPEC: { name: 'Spectrecoin' },
  XST: { name: 'Stealthcoin' },
  XTZ: { name: 'Tezos' },
  XUC: { name: 'Exchange-Union' },
  XVC: { name: 'Vcash' },
  XVG: { name: 'Verge' },
  XWC: { name: 'WhiteCoin' },
  XZC: { name: 'ZCoin' },
  XZR: { name: 'ZrCoin' },
  YEE: { name: 'Yee' },
  YOYOW: { name: 'YOYOW' },
  ZCC: { name: 'ZcCoin' },
  ZCL: { name: 'Zclassic' },
  ZCO: { name: 'Zebi' },
  ZEC: { name: 'Zcash' },
  ZEN: { name: 'ZenCash' },
  ZET: { name: 'Zetacoin' },
  ZIL: { name: 'Zilliqa' },
  ZLA: { name: 'Zilla' },
  ZRX: { name: '0x' }
};
